defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

pull_request_rules:
  - name: backport patches to master branch
    conditions:
      - base=main
      - label=A:backport/master
    actions:
      backport:
        branches:
          - master
