import { FunctionComponent } from "react";
import { SvgImagePop } from "./svg-image-pop";

export const BirthdayLettersSvg: FunctionComponent = () => {
  return (
    <g>
      <SvgImagePop
        x="95"
        y="180"
        width="75"
        height="75"
        href="/bday-letters/b.svg"
      />
      <SvgImagePop
        x="145"
        y="160"
        width="65"
        height="65"
        href="/bday-letters/i.svg"
      />
      <SvgImagePop
        x="195"
        y="145"
        width="75"
        height="75"
        href="/bday-letters/r.svg"
      />
      <SvgImagePop
        x="250"
        y="150"
        width="75"
        height="75"
        href="/bday-letters/t.svg"
      />
      <SvgImagePop
        x="310"
        y="160"
        width="75"
        height="75"
        href="/bday-letters/h.svg"
      />
      <SvgImagePop
        x="380"
        y="150"
        width="75"
        height="75"
        href="/bday-letters/d.svg"
      />
      <SvgImagePop
        x="440"
        y="140"
        width="75"
        height="75"
        href="/bday-letters/a.svg"
      />
      <SvgImagePop
        x="510"
        y="180"
        width="75"
        height="75"
        href="/bday-letters/y.svg"
      />
    </g>
  );
};
