import { MockChains } from "~/config/asset-list/mock-data";

import { AssetLists } from "../mock-asset-lists";

beforeAll(() => {
  jest.spyOn(console, "warn").mockImplementation(() => {});
});

afterAll(() => {
  // eslint-disable-next-line no-console
  (console.warn as jest.Mock).mockRestore();
});

describe("getKeplrCompatibleChain", () => {
  it("should return undefined if assetList is not found and environment is testnet", async () => {
    const assetLists: any[] = [];
    const environment = "testnet";

    const getKeplrCompatibleChain = await import("../utils").then(
      (module) => module.getKeplrCompatibleChain
    );
    const result = getKeplrCompatibleChain({
      chain: MockChains[0],
      assetLists,
      environment,
    });

    expect(result).toBeUndefined();
  });

  it("should return error if assetList is not found and environment is mainnet", async () => {
    const assetLists: any[] = [];
    const environment = "mainnet";

    const getKeplrCompatibleChain = await import("../utils").then(
      (module) => module.getKeplrCompatibleChain
    );

    expect(() =>
      getKeplrCompatibleChain({
        chain: MockChains[0],
        assetLists,
        environment,
      })
    ).toThrow(`Failed to find currencies for ${MockChains[0].chain_name}`);
  });

  it("should return a valid ChainInfoWithExplorer object when assetList is found", async () => {
    const environment = "mainnet";

    const getKeplrCompatibleChain = await import("../utils").then(
      (module) => module.getKeplrCompatibleChain
    );

    const result = getKeplrCompatibleChain({
      chain: MockChains[0],
      assetLists: AssetLists,
      environment,
    });

    expect(result).toMatchInlineSnapshot(`
      {
        "bech32Config": {
          "bech32PrefixAccAddr": "osmo",
          "bech32PrefixAccPub": "osmopub",
          "bech32PrefixConsAddr": "osmovalcons",
          "bech32PrefixConsPub": "osmovalconspub",
          "bech32PrefixValAddr": "osmovaloper",
          "bech32PrefixValPub": "osmovaloperpub",
        },
        "bip44": {
          "coinType": 118,
        },
        "chainId": "osmosis-1",
        "chainName": "osmosis",
        "currencies": [
          {
            "base": "uosmo",
            "coinDecimals": 6,
            "coinDenom": "OSMO",
            "coinGeckoId": "osmosis",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/osmo.svg",
            "coinMinimalDenom": "uosmo",
            "contractAddress": undefined,
            "gasPriceStep": {
              "average": 0.025,
              "high": 0.04,
              "low": 0.0025,
            },
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "uion",
            "coinDecimals": 6,
            "coinDenom": "ION",
            "coinGeckoId": "ion",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/ion.svg",
            "coinMinimalDenom": "uion",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "factory/osmo14klwqgkmackvx2tqa0trtg69dmy0nrg4ntq4gjgw2za4734r5seqjqm4gm/uibcx",
            "coinDecimals": 6,
            "coinDenom": "IBCX",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/ibcx.svg",
            "coinMinimalDenom": "factory/osmo14klwqgkmackvx2tqa0trtg69dmy0nrg4ntq4gjgw2za4734r5seqjqm4gm/uibcx",
            "contractAddress": "osmo14klwqgkmackvx2tqa0trtg69dmy0nrg4ntq4gjgw2za4734r5seqjqm4gm",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "factory/osmo1xqw2sl9zk8a6pch0csaw78n4swg5ws8t62wc5qta4gnjxfqg6v2qcs243k/stuibcx",
            "coinDecimals": 6,
            "coinDenom": "stIBCX",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/stibcx.svg",
            "coinMinimalDenom": "factory/osmo1xqw2sl9zk8a6pch0csaw78n4swg5ws8t62wc5qta4gnjxfqg6v2qcs243k/stuibcx",
            "contractAddress": "osmo1xqw2sl9zk8a6pch0csaw78n4swg5ws8t62wc5qta4gnjxfqg6v2qcs243k",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "factory/osmo1dv8wz09tckslr2wy5z86r46dxvegylhpt97r9yd6qc3kyc6tv42qa89dr9/ampOSMO",
            "coinDecimals": 6,
            "coinDenom": "ampOSMO",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/amposmo.png",
            "coinMinimalDenom": "factory/osmo1dv8wz09tckslr2wy5z86r46dxvegylhpt97r9yd6qc3kyc6tv42qa89dr9/ampOSMO",
            "contractAddress": "osmo1dv8wz09tckslr2wy5z86r46dxvegylhpt97r9yd6qc3kyc6tv42qa89dr9",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "factory/osmo1s794h9rxggytja3a4pmwul53u98k06zy2qtrdvjnfuxruh7s8yjs6cyxgd/ucdt",
            "coinDecimals": 6,
            "coinDenom": "CDT",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/cdt.svg",
            "coinMinimalDenom": "factory/osmo1s794h9rxggytja3a4pmwul53u98k06zy2qtrdvjnfuxruh7s8yjs6cyxgd/ucdt",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "factory/osmo1s794h9rxggytja3a4pmwul53u98k06zy2qtrdvjnfuxruh7s8yjs6cyxgd/umbrn",
            "coinDecimals": 6,
            "coinDenom": "MBRN",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/mbrn.svg",
            "coinMinimalDenom": "factory/osmo1s794h9rxggytja3a4pmwul53u98k06zy2qtrdvjnfuxruh7s8yjs6cyxgd/umbrn",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "factory/osmo1g8qypve6l95xmhgc0fddaecerffymsl7kn9muw/squosmo",
            "coinDecimals": 6,
            "coinDenom": "sqOSMO",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/sqosmo.svg",
            "coinMinimalDenom": "factory/osmo1g8qypve6l95xmhgc0fddaecerffymsl7kn9muw/squosmo",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "factory/osmo1g8qypve6l95xmhgc0fddaecerffymsl7kn9muw/sqatom",
            "coinDecimals": 6,
            "coinDenom": "sqATOM",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/sqatom.svg",
            "coinMinimalDenom": "factory/osmo1g8qypve6l95xmhgc0fddaecerffymsl7kn9muw/sqatom",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "factory/osmo1g8qypve6l95xmhgc0fddaecerffymsl7kn9muw/sqbtc",
            "coinDecimals": 6,
            "coinDenom": "sqBTC",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/sqbtc.svg",
            "coinMinimalDenom": "factory/osmo1g8qypve6l95xmhgc0fddaecerffymsl7kn9muw/sqbtc",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
        ],
        "explorerUrlToTx": "https://www.mintscan.io/cosmos/txs/{txHash}",
        "features": [
          "ibc-go",
          "ibc-transfer",
          "cosmwasm",
          "wasmd_0.24+",
          "osmosis-txfees",
        ],
        "feeCurrencies": [
          {
            "base": "uosmo",
            "coinDecimals": 6,
            "coinDenom": "OSMO",
            "coinGeckoId": "osmosis",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/osmo.svg",
            "coinMinimalDenom": "uosmo",
            "contractAddress": undefined,
            "gasPriceStep": {
              "average": 0.025,
              "high": 0.04,
              "low": 0.0025,
            },
            "type": undefined,
          },
        ],
        "prettyChainName": "Osmosis",
        "rest": "https://lcd-osmosis.keplr.app",
        "rpc": "https://rpc-osmosis.keplr.app",
        "stakeCurrency": {
          "base": "uosmo",
          "coinDecimals": 6,
          "coinDenom": "OSMO",
          "coinGeckoId": "osmosis",
          "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/osmo.svg",
          "coinMinimalDenom": "uosmo",
        },
      }
    `);
  });

  it("should return a valid ChainInfoWithExplorer with all the necessary cw20 tokens properties", async () => {
    const environment = "mainnet";

    const getKeplrCompatibleChain = await import("../utils").then(
      (module) => module.getKeplrCompatibleChain
    );

    const result = getKeplrCompatibleChain({
      chain: MockChains[2],
      assetLists: AssetLists,
      environment,
    });

    expect(result).toMatchInlineSnapshot(`
      {
        "bech32Config": {
          "bech32PrefixAccAddr": "juno",
          "bech32PrefixAccPub": "junopub",
          "bech32PrefixConsAddr": "junovalcons",
          "bech32PrefixConsPub": "junovalconspub",
          "bech32PrefixValAddr": "junovaloper",
          "bech32PrefixValPub": "junovaloperpub",
        },
        "bip44": {
          "coinType": 118,
        },
        "chainId": "juno-1",
        "chainName": "juno",
        "currencies": [
          {
            "base": "ibc/46B44899322F3CD854D2D46DEEF881958467CDD4B3B10086DA49296BBED94BED",
            "coinDecimals": 6,
            "coinDenom": "JUNO",
            "coinGeckoId": "juno-network",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/juno.svg",
            "coinMinimalDenom": "ujuno",
            "contractAddress": undefined,
            "gasPriceStep": {
              "average": 0.1,
              "high": 0.125,
              "low": 0.075,
            },
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/F6B691D5F7126579DDC87357B09D653B47FDCE0A3383FF33C8D8B544FE29A8A6",
            "coinDecimals": 3,
            "coinDenom": "MARBLE",
            "coinGeckoId": "marble",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/marble.svg",
            "coinMinimalDenom": "cw20:juno1g2g7ucurum66d42g8k5twk34yegdq8c82858gz0tq2fc75zy7khssgnhjl:MARBLE",
            "contractAddress": "juno1g2g7ucurum66d42g8k5twk34yegdq8c82858gz0tq2fc75zy7khssgnhjl",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/297C64CC42B5A8D8F82FE2EBE208A6FE8F94B86037FA28C4529A23701C228F7A",
            "coinDecimals": 6,
            "coinDenom": "NETA",
            "coinGeckoId": "neta",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/neta.svg",
            "coinMinimalDenom": "cw20:juno168ctmpyppk90d34p3jjy658zf5a5l3w8wk35wht6ccqj4mr0yv8s4j5awr:NETA",
            "contractAddress": "juno168ctmpyppk90d34p3jjy658zf5a5l3w8wk35wht6ccqj4mr0yv8s4j5awr",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/C2A2E9CA95DDD4828B75124B5E27B8401C7D8493BC48353D418CBFC04565899B",
            "coinDecimals": 6,
            "coinDenom": "HOPE",
            "coinGeckoId": "hope-galaxy",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/hope.svg",
            "coinMinimalDenom": "cw20:juno1re3x67ppxap48ygndmrc7har2cnc7tcxtm9nplcas4v0gc3wnmvs3s807z:HOPE",
            "contractAddress": "juno1re3x67ppxap48ygndmrc7har2cnc7tcxtm9nplcas4v0gc3wnmvs3s807z",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/6BDB4C8CCD45033F9604E4B93ED395008A753E01EECD6992E7D1EA23D9D3B788",
            "coinDecimals": 6,
            "coinDenom": "RAC",
            "coinGeckoId": "racoon",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/rac.svg",
            "coinMinimalDenom": "cw20:juno1r4pzw8f9z0sypct5l9j906d47z998ulwvhvqe5xdwgy8wf84583sxwh0pa:RAC",
            "contractAddress": "juno1r4pzw8f9z0sypct5l9j906d47z998ulwvhvqe5xdwgy8wf84583sxwh0pa",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/DB9755CB6FE55192948AE074D18FA815E1429D3D374D5BDA8D89623C6CF235C3",
            "coinDecimals": 6,
            "coinDenom": "BLOCK",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/block.svg",
            "coinMinimalDenom": "cw20:juno1y9rf7ql6ffwkv02hsgd4yruz23pn4w97p75e2slsnkm0mnamhzysvqnxaq:BLOCK",
            "contractAddress": "juno1y9rf7ql6ffwkv02hsgd4yruz23pn4w97p75e2slsnkm0mnamhzysvqnxaq",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/52E12CF5CA2BB903D84F5298B4BFD725D66CAB95E09AA4FC75B2904CA5485FEB",
            "coinDecimals": 0,
            "coinDenom": "DHK",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/dhk.svg",
            "coinMinimalDenom": "cw20:juno1tdjwrqmnztn2j3sj2ln9xnyps5hs48q3ddwjrz7jpv6mskappjys5czd49:DHK",
            "contractAddress": "juno1tdjwrqmnztn2j3sj2ln9xnyps5hs48q3ddwjrz7jpv6mskappjys5czd49",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/00B6E60AD3D65CBEF5579AC8AF609527C0B57535B6E32D96C80A735344FD9DCC",
            "coinDecimals": 6,
            "coinDenom": "RAW",
            "coinGeckoId": "junoswap-raw-dao",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/raw.svg",
            "coinMinimalDenom": "cw20:juno15u3dt79t6sxxa3x3kpkhzsy56edaa5a66wvt3kxmukqjz2sx0hes5sn38g:RAW",
            "contractAddress": "juno15u3dt79t6sxxa3x3kpkhzsy56edaa5a66wvt3kxmukqjz2sx0hes5sn38g",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/AA1C80225BCA7B32ED1FC6ABF8B8E899BEB48ECDB4B417FD69873C6D715F97E7",
            "coinDecimals": 6,
            "coinDenom": "ASVT",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/asvt.png",
            "coinMinimalDenom": "cw20:juno17wzaxtfdw5em7lc94yed4ylgjme63eh73lm3lutp2rhcxttyvpwsypjm4w:ASVT",
            "contractAddress": "juno17wzaxtfdw5em7lc94yed4ylgjme63eh73lm3lutp2rhcxttyvpwsypjm4w",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/0CB9DB3441D0D50F35699DEE22B9C965487E83FB2D9F483D1CC5CA34E856C484",
            "coinDecimals": 6,
            "coinDenom": "JOE",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/joe.png",
            "coinMinimalDenom": "cw20:juno1n7n7d5088qlzlj37e9mgmkhx6dfgtvt02hqxq66lcap4dxnzdhwqfmgng3:JOE",
            "contractAddress": "juno1n7n7d5088qlzlj37e9mgmkhx6dfgtvt02hqxq66lcap4dxnzdhwqfmgng3",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/52C57FCA7D6854AA178E7A183DDBE4EF322B904B1D719FC485F6FFBC1F72A19E",
            "coinDecimals": 6,
            "coinDenom": "GLTO",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/glto.svg",
            "coinMinimalDenom": "cw20:juno1j0a9ymgngasfn3l5me8qpd53l5zlm9wurfdk7r65s5mg6tkxal3qpgf5se:GLTO",
            "contractAddress": "juno1j0a9ymgngasfn3l5me8qpd53l5zlm9wurfdk7r65s5mg6tkxal3qpgf5se",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/7C781B4C2082CD62129A972D47486D78EC17155C299270E3C89348EA026BEAF8",
            "coinDecimals": 6,
            "coinDenom": "GKEY",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/gkey.svg",
            "coinMinimalDenom": "cw20:juno1gz8cf86zr4vw9cjcyyv432vgdaecvr9n254d3uwwkx9rermekddsxzageh:GKEY",
            "contractAddress": "juno1gz8cf86zr4vw9cjcyyv432vgdaecvr9n254d3uwwkx9rermekddsxzageh",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/C6B6BFCB6EE49A7CAB1A7E7B021DE35B99D525AC660844952F0F6C78DCB2A57B",
            "coinDecimals": 6,
            "coinDenom": "SEJUNO",
            "coinGeckoId": "stakeeasy-juno-derivative",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/sejuno.svg",
            "coinMinimalDenom": "cw20:juno1dd0k0um5rqncfueza62w9sentdfh3ec4nw4aq4lk5hkjl63vljqscth9gv:SEJUNO",
            "contractAddress": "juno1dd0k0um5rqncfueza62w9sentdfh3ec4nw4aq4lk5hkjl63vljqscth9gv",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/C2DF5C3949CA835B221C575625991F09BAB4E48FB9C11A4EE357194F736111E3",
            "coinDecimals": 6,
            "coinDenom": "BJUNO",
            "coinGeckoId": "stakeeasy-bjuno",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/bjuno.svg",
            "coinMinimalDenom": "cw20:juno1wwnhkagvcd3tjz6f8vsdsw5plqnw8qy2aj3rrhqr2axvktzv9q2qz8jxn3:BJUNO",
            "contractAddress": "juno1wwnhkagvcd3tjz6f8vsdsw5plqnw8qy2aj3rrhqr2axvktzv9q2qz8jxn3",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/C3FC4DED273E7D1DD2E7BAA3317EC9A53CD3252B577AA33DC00D9DF2BDF3ED5C",
            "coinDecimals": 6,
            "coinDenom": "SOLAR",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/solar.svg",
            "coinMinimalDenom": "cw20:juno159q8t5g02744lxq8lfmcn6f78qqulq9wn3y9w7lxjgkz4e0a6kvsfvapse:SOLAR",
            "contractAddress": "juno159q8t5g02744lxq8lfmcn6f78qqulq9wn3y9w7lxjgkz4e0a6kvsfvapse",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/18A676A074F73B9B42DA4F9DFC8E5AEF334C9A6636DDEC8D34682F52F1DECDF6",
            "coinDecimals": 6,
            "coinDenom": "SEASY",
            "coinGeckoId": "seasy",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/seasy.svg",
            "coinMinimalDenom": "cw20:juno19rqljkh95gh40s7qdx40ksx3zq5tm4qsmsrdz9smw668x9zdr3lqtg33mf:SEASY",
            "contractAddress": "juno19rqljkh95gh40s7qdx40ksx3zq5tm4qsmsrdz9smw668x9zdr3lqtg33mf",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/6B982170CE024689E8DD0E7555B129B488005130D4EDA426733D552D10B36D8F",
            "coinDecimals": 6,
            "coinDenom": "MUSE",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/muse.png",
            "coinMinimalDenom": "cw20:juno1p8x807f6h222ur0vssqy3qk6mcpa40gw2pchquz5atl935t7kvyq894ne3:MUSE",
            "contractAddress": "juno1p8x807f6h222ur0vssqy3qk6mcpa40gw2pchquz5atl935t7kvyq894ne3",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/7CE5F388D661D82A0774E47B5129DA51CC7129BD1A70B5FA6BCEBB5B0A2FAEAF",
            "coinDecimals": 6,
            "coinDenom": "FURY",
            "coinGeckoId": "fanfury",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/fury.png",
            "coinMinimalDenom": "cw20:juno1cltgm8v842gu54srmejewghnd6uqa26lzkpa635wzra9m9xuudkqa2gtcz:FURY",
            "contractAddress": "juno1cltgm8v842gu54srmejewghnd6uqa26lzkpa635wzra9m9xuudkqa2gtcz",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/D3B574938631B0A1BA704879020C696E514CFADAA7643CDE4BD5EB010BDE327B",
            "coinDecimals": 6,
            "coinDenom": "PHMN",
            "coinGeckoId": "posthuman",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/phmn.svg",
            "coinMinimalDenom": "cw20:juno1rws84uz7969aaa7pej303udhlkt3j9ca0l3egpcae98jwak9quzq8szn2l:PHMN",
            "contractAddress": "juno1rws84uz7969aaa7pej303udhlkt3j9ca0l3egpcae98jwak9quzq8szn2l",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/D3ADAF73F84CDF205BCB72C142FDAEEA2C612AB853CEE6D6C06F184FA38B1099",
            "coinDecimals": 6,
            "coinDenom": "HOPERS",
            "coinGeckoId": "hopers-io ",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/hopers.svg",
            "coinMinimalDenom": "cw20:juno1u45shlp0q4gcckvsj06ss4xuvsu0z24a0d0vr9ce6r24pht4e5xq7q995n:HOPERS",
            "contractAddress": "juno1u45shlp0q4gcckvsj06ss4xuvsu0z24a0d0vr9ce6r24pht4e5xq7q995n",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/2FBAC4BF296D7844796844B35978E5899984BA5A6314B2DD8F83C215550010B3",
            "coinDecimals": 6,
            "coinDenom": "WYND",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/wynd.svg",
            "coinMinimalDenom": "cw20:juno1mkw83sv6c7sjdvsaplrzc8yaes9l42p4mhy0ssuxjnyzl87c9eps7ce3m9:WYND",
            "contractAddress": "juno1mkw83sv6c7sjdvsaplrzc8yaes9l42p4mhy0ssuxjnyzl87c9eps7ce3m9",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/E750D31033DC1CF4A044C3AA0A8117401316DC918FBEBC4E3D34F91B09D5F54C",
            "coinDecimals": 6,
            "coinDenom": "NRIDE",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/nride.svg",
            "coinMinimalDenom": "cw20:juno1qmlchtmjpvu0cr7u0tad2pq8838h6farrrjzp39eqa9xswg7teussrswlq:NRIDE",
            "contractAddress": "juno1qmlchtmjpvu0cr7u0tad2pq8838h6farrrjzp39eqa9xswg7teussrswlq",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/4F24D904BAB5FFBD3524F2DE3EC3C7A9E687A2408D9A985E57B356D9FA9201C6",
            "coinDecimals": 6,
            "coinDenom": "FOX",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/fox.png",
            "coinMinimalDenom": "cw20:juno1u8cr3hcjvfkzxcaacv9q75uw9hwjmn8pucc93pmy6yvkzz79kh3qncca8x:FOX",
            "contractAddress": "juno1u8cr3hcjvfkzxcaacv9q75uw9hwjmn8pucc93pmy6yvkzz79kh3qncca8x",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/BAC9C6998F1F5C316D3353622EAEDAF8BD00FAABEB374FECDF8C9BC475172CFA",
            "coinDecimals": 6,
            "coinDenom": "GRDN",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/grdn.png",
            "coinMinimalDenom": "cw20:juno1xekkh27punj0uxruv3gvuydyt856fax0nu750xns99t2qcxp7xmsqwhfma:GRDN",
            "contractAddress": "juno1xekkh27punj0uxruv3gvuydyt856fax0nu750xns99t2qcxp7xmsqwhfma",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/DC0D3303BBE739E073224D0314385B88B247F56D71D726A91414CCA244FFFE7E",
            "coinDecimals": 6,
            "coinDenom": "MNPU",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/mnpu.svg",
            "coinMinimalDenom": "cw20:juno166heaxlyntd33a5euh4rrz26svhean4klzw594esmd02l4atan6sazy2my:MNPU",
            "contractAddress": "juno166heaxlyntd33a5euh4rrz26svhean4klzw594esmd02l4atan6sazy2my",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/447A0DCE83691056289503DDAB8EB08E52E167A73629F2ACC59F056B92F51CE8",
            "coinDecimals": 6,
            "coinDenom": "SHIBAC",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/shibac.png",
            "coinMinimalDenom": "cw20:juno1x5qt47rw84c4k6xvvywtrd40p8gxjt8wnmlahlqg07qevah3f8lqwxfs7z:SHIBAC",
            "contractAddress": "juno1x5qt47rw84c4k6xvvywtrd40p8gxjt8wnmlahlqg07qevah3f8lqwxfs7z",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/71066B030D8FC6479E638580E1BA9C44925E8C1F6E45036669D22017CFDC8C5E",
            "coinDecimals": 6,
            "coinDenom": "SKOJ",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/skoj.svg",
            "coinMinimalDenom": "cw20:juno1qqwf3lkfjhp77yja7gmg3y95pda0e5xctqrdhf3wvwdd79flagvqfgrgxp:SKOJ",
            "contractAddress": "juno1qqwf3lkfjhp77yja7gmg3y95pda0e5xctqrdhf3wvwdd79flagvqfgrgxp",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/0E4FA664327BD40B32803EE84A77F145834C0281B7F82B65521333B3669FA0BA",
            "coinDecimals": 6,
            "coinDenom": "CLST",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/clst.png",
            "coinMinimalDenom": "cw20:juno1ngww7zxak55fql42wmyqrr4rhzpne24hhs4p3w4cwhcdgqgr3hxsmzl9zg:CLST",
            "contractAddress": "juno1ngww7zxak55fql42wmyqrr4rhzpne24hhs4p3w4cwhcdgqgr3hxsmzl9zg",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/8AEEA9B9304392070F72611076C0E328CE3F2DECA1E18557E36F9DB4F09C0156",
            "coinDecimals": 6,
            "coinDenom": "OSDOGE",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/osdoge.png",
            "coinMinimalDenom": "cw20:juno1ytymtllllsp3hfmndvcp802p2xmy5s8m59ufel8xv9ahyxyfs4hs4kd4je:OSDOGE",
            "contractAddress": "juno1ytymtllllsp3hfmndvcp802p2xmy5s8m59ufel8xv9ahyxyfs4hs4kd4je",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/1EB03F13F29FEA73444586FC4E88A8C14ACE9291501E9658E3BEF951EA4AC85D",
            "coinDecimals": 6,
            "coinDenom": "APEMOS",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/apemos.png",
            "coinMinimalDenom": "cw20:juno1jrr0tuuzxrrwcg6hgeqhw5wqpck2y55734e7zcrp745aardlp0qqg8jz06:APEMOS",
            "contractAddress": "juno1jrr0tuuzxrrwcg6hgeqhw5wqpck2y55734e7zcrp745aardlp0qqg8jz06",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/3DB1721541C94AD19D7735FECED74C227E13F925BDB814392980B40A19C1ED54",
            "coinDecimals": 6,
            "coinDenom": "INVDRS",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/invdrs.png",
            "coinMinimalDenom": "cw20:juno1jwdy7v4egw36pd84aeks3ww6n8k7zhsumd4ac8q5lts83ppxueus4626e8:INVDRS",
            "contractAddress": "juno1jwdy7v4egw36pd84aeks3ww6n8k7zhsumd4ac8q5lts83ppxueus4626e8",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/04BE4E9C825ED781F9684A1226114BB49607500CAD855F1E3FEEC18532297250",
            "coinDecimals": 6,
            "coinDenom": "DOGA",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/doga.png",
            "coinMinimalDenom": "cw20:juno1k2ruzzvvwwtwny6gq6kcwyfhkzahaunp685wmz4hafplduekj98q9hgs6d:DOGA",
            "contractAddress": "juno1k2ruzzvvwwtwny6gq6kcwyfhkzahaunp685wmz4hafplduekj98q9hgs6d",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/F4A07138CAEF0BFB4889E03C44C57956A48631061F1C8AB80421C1F229C1B835",
            "coinDecimals": 6,
            "coinDenom": "CATMOS",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/catmos.png",
            "coinMinimalDenom": "cw20:juno1f5datjdse3mdgrapwuzs3prl7pvxxht48ns6calnn0t77v2s9l8s0qu488:CATMOS",
            "contractAddress": "juno1f5datjdse3mdgrapwuzs3prl7pvxxht48ns6calnn0t77v2s9l8s0qu488",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/56B988C4D934FB7503F5EA9B440C75D489C8AD5D193715B477BEC4F84B8BBA2A",
            "coinDecimals": 6,
            "coinDenom": "SUMMIT",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/summit.png",
            "coinMinimalDenom": "cw20:juno1j4ux0f6gt7e82z7jdpm25v4g2gts880ap64rdwa49989wzhd0dfqed6vqm:SUMMIT",
            "contractAddress": "juno1j4ux0f6gt7e82z7jdpm25v4g2gts880ap64rdwa49989wzhd0dfqed6vqm",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/7A496DB7C2277D4B74EC4428DDB5AC8A62816FBD0DEBE1CFE094935D746BE19C",
            "coinDecimals": 6,
            "coinDenom": "SPACER",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/spacer.png",
            "coinMinimalDenom": "cw20:juno1dyyf7pxeassxvftf570krv7fdf5r8e4r04mp99h0mllsqzp3rs4q7y8yqg:SPACER",
            "contractAddress": "juno1dyyf7pxeassxvftf570krv7fdf5r8e4r04mp99h0mllsqzp3rs4q7y8yqg",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/3DC08BDF2689978DBCEE28C7ADC2932AA658B2F64B372760FBC5A0058669AD29",
            "coinDecimals": 9,
            "coinDenom": "LIGHT",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/light.png",
            "coinMinimalDenom": "cw20:juno1dpany8c0lj526lsa02sldv7shzvnw5dt5ues72rk35hd69rrydxqeraz8l:LIGHT",
            "contractAddress": "juno1dpany8c0lj526lsa02sldv7shzvnw5dt5ues72rk35hd69rrydxqeraz8l",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/912275A63A565BFD80734AEDFFB540132C51E446EAC41483B26EDE8A557C71CF",
            "coinDecimals": 6,
            "coinDenom": "MILE",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/mile.png",
            "coinMinimalDenom": "cw20:juno1llg7q2d5dqlrqzh5dxv8c7kzzjszld34s5vktqmlmaaxqjssz43sxyhq0d:MILE",
            "contractAddress": "juno1llg7q2d5dqlrqzh5dxv8c7kzzjszld34s5vktqmlmaaxqjssz43sxyhq0d",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/980A2748F37C938AD129B92A51E2ABA8CFFC6862ADD61EC1B291125535DBE30B",
            "coinDecimals": 6,
            "coinDenom": "MANNA",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/manna.png",
            "coinMinimalDenom": "cw20:juno13ca2g36ng6etcfhr9qxx352uw2n5e92np54thfkm3w3nzlhsgvwsjaqlyq:MANNA",
            "contractAddress": "juno13ca2g36ng6etcfhr9qxx352uw2n5e92np54thfkm3w3nzlhsgvwsjaqlyq",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/593F820ECE676A3E0890C734EC4F3A8DE16EC10A54EEDFA8BDFEB40EEA903960",
            "coinDecimals": 6,
            "coinDenom": "VOID",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/void.png",
            "coinMinimalDenom": "cw20:juno1lpvx3mv2a6ddzfjc7zzz2v2cm5gqgqf0hx67hc5p5qwn7hz4cdjsnznhu8:VOID",
            "contractAddress": "juno1lpvx3mv2a6ddzfjc7zzz2v2cm5gqgqf0hx67hc5p5qwn7hz4cdjsnznhu8",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/5164ECF584AD7DC27DA9E6A89E75DAB0F7C4FCB0A624B69215B8BC6A2C40CD07",
            "coinDecimals": 6,
            "coinDenom": "SLCA",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/slca.png",
            "coinMinimalDenom": "cw20:juno10vgf2u03ufcf25tspgn05l7j3tfg0j63ljgpffy98t697m5r5hmqaw95ux:SLCA",
            "contractAddress": "juno10vgf2u03ufcf25tspgn05l7j3tfg0j63ljgpffy98t697m5r5hmqaw95ux",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/C00B17F74C94449A62935B4C886E6F0F643249A270DEF269D53CE6741ECCDB93",
            "coinDecimals": 6,
            "coinDenom": "PEPEC",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/pepec.png",
            "coinMinimalDenom": "cw20:juno1epxnvge53c4hkcmqzlxryw5fp7eae2utyk6ehjcfpwajwp48km3sgxsh9k:PEPEC",
            "contractAddress": "juno1epxnvge53c4hkcmqzlxryw5fp7eae2utyk6ehjcfpwajwp48km3sgxsh9k",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/2F5C084037D951B24D100F15CC013A131DF786DCE1B1DBDC48F018A9B9A138DE",
            "coinDecimals": 6,
            "coinDenom": "CASA",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/casa.png",
            "coinMinimalDenom": "cw20:juno1ju8k8sqwsqu5k6umrypmtyqu2wqcpnrkf4w4mntvl0javt4nma7s8lzgss:CASA",
            "contractAddress": "juno1ju8k8sqwsqu5k6umrypmtyqu2wqcpnrkf4w4mntvl0javt4nma7s8lzgss",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/AABCB14ACAFD53A5C455BAC01EA0CA5AE18714895846681A52BFF1E3B960B44E",
            "coinDecimals": 6,
            "coinDenom": "WATR",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/watr.png",
            "coinMinimalDenom": "cw20:juno1m4h8q4p305wgy7vkux0w6e5ylhqll3s6pmadhxkhqtuwd5wlxhxs8xklsw:WATR",
            "contractAddress": "juno1m4h8q4p305wgy7vkux0w6e5ylhqll3s6pmadhxkhqtuwd5wlxhxs8xklsw",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "cw20",
          },
          {
            "base": "ibc/D69F6D787EC649F4E998161A9F0646F4C2DCC64748A2AB982F14CAFBA7CC0EC9",
            "coinDecimals": 6,
            "coinDenom": "DGL",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/dgl.png",
            "coinMinimalDenom": "factory/juno1u805lv20qc6jy7c3ttre7nct6uyl20pfky5r7e/DGL",
            "contractAddress": "juno1u805lv20qc6jy7c3ttre7nct6uyl20pfky5r7e",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
        ],
        "explorerUrlToTx": "https://www.mintscan.io/juno/txs/{txHash}",
        "features": [
          "ibc-transfer",
          "ibc-go",
          "cosmwasm",
          "wasmd_0.24+",
        ],
        "feeCurrencies": [
          {
            "base": "ibc/46B44899322F3CD854D2D46DEEF881958467CDD4B3B10086DA49296BBED94BED",
            "coinDecimals": 6,
            "coinDenom": "JUNO",
            "coinGeckoId": "juno-network",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/juno.svg",
            "coinMinimalDenom": "ujuno",
            "contractAddress": undefined,
            "gasPriceStep": {
              "average": 0.1,
              "high": 0.125,
              "low": 0.075,
            },
            "type": undefined,
          },
        ],
        "prettyChainName": "Juno",
        "rest": "https://lcd-juno.keplr.app",
        "rpc": "https://rpc-juno.keplr.app",
        "stakeCurrency": {
          "base": "ibc/46B44899322F3CD854D2D46DEEF881958467CDD4B3B10086DA49296BBED94BED",
          "coinDecimals": 6,
          "coinDenom": "JUNO",
          "coinGeckoId": "juno-network",
          "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/juno.svg",
          "coinMinimalDenom": "ujuno",
        },
      }
    `);
  });

  it("should return asset within currencies even if the display and denom unit denom differ", async () => {
    const environment = "mainnet";

    const getKeplrCompatibleChain = await import("../utils").then(
      (module) => module.getKeplrCompatibleChain
    );

    const result = getKeplrCompatibleChain({
      chain: MockChains[3], // Injective
      assetLists: AssetLists,
      environment,
    });

    expect(result).toMatchInlineSnapshot(`
      {
        "bech32Config": {
          "bech32PrefixAccAddr": "inj",
          "bech32PrefixAccPub": "injpub",
          "bech32PrefixConsAddr": "injvalcons",
          "bech32PrefixConsPub": "injvalconspub",
          "bech32PrefixValAddr": "injvaloper",
          "bech32PrefixValPub": "injvaloperpub",
        },
        "bip44": {
          "coinType": 60,
        },
        "chainId": "injective-1",
        "chainName": "injective",
        "currencies": [
          {
            "base": "ibc/64BA6E31FE887D66C6F8F31C7B1A80C7CA179239677B4088BB55F5EA07DBE273",
            "coinDecimals": 18,
            "coinDenom": "INJ",
            "coinGeckoId": "injective-protocol",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/inj.svg",
            "coinMinimalDenom": "inj",
            "contractAddress": undefined,
            "gasPriceStep": {
              "average": 700000000,
              "high": 900000000,
              "low": 500000000,
            },
            "pegMechanism": undefined,
            "type": undefined,
          },
        ],
        "explorerUrlToTx": "https://explorer.injective.network/transaction/{txHash}",
        "features": [
          "ibc-transfer",
          "ibc-go",
          "eth-address-gen",
          "eth-key-sign",
        ],
        "feeCurrencies": [
          {
            "base": "ibc/64BA6E31FE887D66C6F8F31C7B1A80C7CA179239677B4088BB55F5EA07DBE273",
            "coinDecimals": 18,
            "coinDenom": "INJ",
            "coinGeckoId": "injective-protocol",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/inj.svg",
            "coinMinimalDenom": "inj",
            "contractAddress": undefined,
            "gasPriceStep": {
              "average": 700000000,
              "high": 900000000,
              "low": 500000000,
            },
            "type": undefined,
          },
        ],
        "prettyChainName": "Injective",
        "rest": "https://public.lcd.injective.network",
        "rpc": "https://public.api.injective.network",
        "stakeCurrency": {
          "base": "ibc/64BA6E31FE887D66C6F8F31C7B1A80C7CA179239677B4088BB55F5EA07DBE273",
          "coinDecimals": 18,
          "coinDenom": "INJ",
          "coinGeckoId": "injective-protocol",
          "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/inj.svg",
          "coinMinimalDenom": "inj",
        },
      }
    `);
  });

  it("should return a valid ChainInfoWithExplorer with all the necessary secret20 tokens properties", async () => {
    const environment = "mainnet";

    const getKeplrCompatibleChain = await import("../utils").then(
      (module) => module.getKeplrCompatibleChain
    );

    const result = getKeplrCompatibleChain({
      chain: MockChains[4],
      assetLists: AssetLists,
      environment,
    });

    expect(result).toMatchInlineSnapshot(`
      {
        "bech32Config": {
          "bech32PrefixAccAddr": "secret",
          "bech32PrefixAccPub": "secretpub",
          "bech32PrefixConsAddr": "secretvalcons",
          "bech32PrefixConsPub": "secretvalconspub",
          "bech32PrefixValAddr": "secretvaloper",
          "bech32PrefixValPub": "secretvaloperpub",
        },
        "bip44": {
          "coinType": 529,
        },
        "chainId": "secret-4",
        "chainName": "secretnetwork",
        "currencies": [
          {
            "base": "ibc/0954E1C28EB7AF5B72D24F3BC2B47BBB2FDF91BDDFD57B74B99E133AED40972A",
            "coinDecimals": 6,
            "coinDenom": "SCRT",
            "coinGeckoId": "secret",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/scrt.svg",
            "coinMinimalDenom": "uscrt",
            "contractAddress": undefined,
            "gasPriceStep": {
              "average": 0.1,
              "high": 0.25,
              "low": 0.1,
            },
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/A6383B6CF5EA23E067666C06BC34E2A96869927BD9744DC0C1643E589C710AA3",
            "coinDecimals": 6,
            "coinDenom": "ALTER",
            "coinGeckoId": "alter",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/alter.svg",
            "coinMinimalDenom": "cw20:secret12rcvz0umvk875kd6a803txhtlu7y0pnd73kcej:ALTER",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "secret20",
          },
          {
            "base": "ibc/1FBA9E763B8679BEF7BAAAF2D16BCA78C3B297D226C3F31312C769D7B8F992D8",
            "coinDecimals": 6,
            "coinDenom": "BUTT",
            "coinGeckoId": "buttcoin-2",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/butt.svg",
            "coinMinimalDenom": "cw20:secret1yxcexylwyxlq58umhgsjgstgcg2a0ytfy4d9lt:BUTT",
            "contractAddress": "secret1yxcexylwyxlq58umhgsjgstgcg2a0ytfy4d9lt",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "secret20",
          },
          {
            "base": "ibc/71055835C7639739EAE03AACD1324FE162DBA41D09F197CB72D966D014225B1C",
            "coinDecimals": 8,
            "coinDenom": "SHD(old)",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/shd(old).svg",
            "coinMinimalDenom": "cw20:secret1qfql357amn448duf5gvp9gr48sxx9tsnhupu3d:SHD(old)",
            "contractAddress": "secret1qfql357amn448duf5gvp9gr48sxx9tsnhupu3d",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "secret20",
          },
          {
            "base": "ibc/9A8A93D04917A149C8AC7C16D3DA8F470D59E8D867499C4DA97450E1D7363213",
            "coinDecimals": 18,
            "coinDenom": "SIENNA",
            "coinGeckoId": "sienna",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/sienna.svg",
            "coinMinimalDenom": "cw20:secret1rgm2m5t530tdzyd99775n6vzumxa5luxcllml4:SIENNA",
            "contractAddress": "secret1rgm2m5t530tdzyd99775n6vzumxa5luxcllml4",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "secret20",
          },
          {
            "base": "ibc/D0E5BF2940FB58D9B283A339032DE88111407AAD7D94A7F1F3EB78874F8616D4",
            "coinDecimals": 6,
            "coinDenom": "stkd-SCRT",
            "coinGeckoId": "stkd-scrt",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/stkd-scrt.svg",
            "coinMinimalDenom": "cw20:secret1k6u0cy4feepm6pehnz804zmwakuwdapm69tuc4:stkd-SCRT",
            "contractAddress": "secret1k6u0cy4feepm6pehnz804zmwakuwdapm69tuc4",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "secret20",
          },
          {
            "base": "ibc/18A1B70E3205A48DE8590C0D11030E7146CDBF1048789261D53FFFD7527F8B55",
            "coinDecimals": 6,
            "coinDenom": "AMBER",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/amber.svg",
            "coinMinimalDenom": "cw20:secret1s09x2xvfd2lp2skgzm29w2xtena7s8fq98v852:AMBER",
            "contractAddress": "secret1s09x2xvfd2lp2skgzm29w2xtena7s8fq98v852",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "secret20",
          },
          {
            "base": "ibc/8A025A1E70101E39DE0C0F153E582A30806D3DA16795F6D868A3AA247D2DEDF7",
            "coinDecimals": 6,
            "coinDenom": "SILK",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/silk.svg",
            "coinMinimalDenom": "cw20:secret1fl449muk5yq8dlad7a22nje4p5d2pnsgymhjfd:SILK",
            "contractAddress": "secret1fl449muk5yq8dlad7a22nje4p5d2pnsgymhjfd",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "secret20",
          },
          {
            "base": "ibc/0B3D528E74E3DEAADF8A68F393887AC7E06028904D02173561B0D27F6E751D0A",
            "coinDecimals": 8,
            "coinDenom": "SHD",
            "coinGeckoId": "shade-protocol",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/shd.svg",
            "coinMinimalDenom": "cw20:secret153wu605vvp934xhd4k9dtd640zsep5jkesstdm:SHD",
            "contractAddress": "secret153wu605vvp934xhd4k9dtd640zsep5jkesstdm",
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": "secret20",
          },
        ],
        "explorerUrlToTx": "https://secretnodes.com/secret/chains/secret-4/transactions/{txHash}",
        "features": [
          "ibc-transfer",
          "ibc-go",
          "secretwasm",
          "cosmwasm",
          "wasmd_0.24+",
        ],
        "feeCurrencies": [
          {
            "base": "ibc/0954E1C28EB7AF5B72D24F3BC2B47BBB2FDF91BDDFD57B74B99E133AED40972A",
            "coinDecimals": 6,
            "coinDenom": "SCRT",
            "coinGeckoId": "secret",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/scrt.svg",
            "coinMinimalDenom": "uscrt",
            "contractAddress": undefined,
            "gasPriceStep": {
              "average": 0.1,
              "high": 0.25,
              "low": 0.1,
            },
            "type": undefined,
          },
        ],
        "prettyChainName": "Secret Network",
        "rest": "https://lcd-secret.keplr.app",
        "rpc": "https://rpc-secret.keplr.app",
        "stakeCurrency": {
          "base": "ibc/0954E1C28EB7AF5B72D24F3BC2B47BBB2FDF91BDDFD57B74B99E133AED40972A",
          "coinDecimals": 6,
          "coinDenom": "SCRT",
          "coinGeckoId": "secret",
          "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/scrt.svg",
          "coinMinimalDenom": "uscrt",
        },
      }
    `);
  });

  it("should return a valid ChainInfoWithExplorer with pegMechanism if it's available", async () => {
    const environment = "mainnet";

    const getKeplrCompatibleChain = await import("../utils").then(
      (module) => module.getKeplrCompatibleChain
    );

    const result = getKeplrCompatibleChain({
      chain: MockChains[5],
      assetLists: AssetLists,
      environment,
    });

    expect(result).toMatchInlineSnapshot(`
      {
        "bech32Config": {
          "bech32PrefixAccAddr": "axelar",
          "bech32PrefixAccPub": "axelarpub",
          "bech32PrefixConsAddr": "axelarvalcons",
          "bech32PrefixConsPub": "axelarvalconspub",
          "bech32PrefixValAddr": "axelarvaloper",
          "bech32PrefixValPub": "axelarvaloperpub",
        },
        "bip44": {
          "coinType": 118,
        },
        "chainId": "axelar-dojo-1",
        "chainName": "axelar",
        "currencies": [
          {
            "base": "ibc/D189335C6E4A68B513C10AB227BF1C1D38C746766278BA3EEB4FB14124F1D858",
            "coinDecimals": 6,
            "coinDenom": "USDC.axl",
            "coinGeckoId": "axlusdc",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/usdc.axl.svg",
            "coinMinimalDenom": "uusdc",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": "collateralized",
            "type": undefined,
          },
          {
            "base": "ibc/EA1D43981D5C9A1C4AAEA9C23BB1D4FA126BA9BC7020A25E0AE4AA841EA25DC5",
            "coinDecimals": 18,
            "coinDenom": "ETH",
            "coinGeckoId": "ethereum",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/eth.png",
            "coinMinimalDenom": "weth-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/D1542AA8762DB13087D8364F3EA6509FD6F009A34F00426AF9E4F9FA85CBBF1F",
            "coinDecimals": 8,
            "coinDenom": "WBTC",
            "coinGeckoId": "wrapped-bitcoin",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/wbtc.svg",
            "coinMinimalDenom": "wbtc-satoshi",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/8242AD24008032E457D2E12D46588FD39FB54FB29680C6C7663D296B383C37C4",
            "coinDecimals": 6,
            "coinDenom": "USDT.axl",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/usdt.axl.svg",
            "coinMinimalDenom": "uusdt",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": "collateralized",
            "type": undefined,
          },
          {
            "base": "ibc/0CD3A0285E1341859B5E86B6AB7682F023D03E97607CCC1DC95706411D866DF7",
            "coinDecimals": 18,
            "coinDenom": "DAI",
            "coinGeckoId": "dai",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/dai.svg",
            "coinMinimalDenom": "dai-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": "collateralized",
            "type": undefined,
          },
          {
            "base": "ibc/6329DD8CF31A334DD5BE3F68C846C9FE313281362B37686A62343BAC1EB1546D",
            "coinDecimals": 18,
            "coinDenom": "BUSD",
            "coinGeckoId": "binance-usd",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/busd.svg",
            "coinMinimalDenom": "busd-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/F4A070A6D78496D53127EA85C094A9EC87DFC1F36071B8CCDDBD020F933D213D",
            "coinDecimals": 18,
            "coinDenom": "BNB",
            "coinGeckoId": "binancecoin",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/bnb.svg",
            "coinMinimalDenom": "wbnb-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/AB589511ED0DD5FA56171A39978AFBF1371DB986EC1C3526CE138A16377E39BB",
            "coinDecimals": 18,
            "coinDenom": "MATIC",
            "coinGeckoId": "matic-network",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/matic.png",
            "coinMinimalDenom": "wmatic-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/6F62F01D913E3FFE472A38C78235B8F021B511BC6596ADFF02615C8F83D3B373",
            "coinDecimals": 18,
            "coinDenom": "AVAX",
            "coinGeckoId": "avalanche-2",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/avax.png",
            "coinMinimalDenom": "wavax-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/3FF92D26B407FD61AE95D975712A7C319CDE28DE4D80BDC9978D935932B991D7",
            "coinDecimals": 10,
            "coinDenom": "DOT.axl",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/dot.axl.svg",
            "coinMinimalDenom": "dot-planck",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/0E43EDE2E2A3AFA36D0CD38BDDC0B49FECA64FA426A82E102F304E430ECF46EE",
            "coinDecimals": 18,
            "coinDenom": "FRAX",
            "coinGeckoId": "frax",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/frax.svg",
            "coinMinimalDenom": "frax-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": "hybrid",
            "type": undefined,
          },
          {
            "base": "ibc/D3327A763C23F01EC43D1F0DB3CEFEC390C362569B6FD191F40A5192F8960049",
            "coinDecimals": 18,
            "coinDenom": "LINK",
            "coinGeckoId": "chainlink",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/link.svg",
            "coinMinimalDenom": "link-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/384E5DD50BDE042E1AAF51F312B55F08F95BC985C503880189258B4D9374CBBE",
            "coinDecimals": 18,
            "coinDenom": "AAVE",
            "coinGeckoId": "aave",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/aave.svg",
            "coinMinimalDenom": "aave-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/F83CC6471DA4D4B508F437244F10B9E4C68975344E551A2DEB6B8617AB08F0D4",
            "coinDecimals": 18,
            "coinDenom": "APE",
            "coinGeckoId": "apecoin",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/ape.svg",
            "coinMinimalDenom": "ape-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/6C0CB8653012DC2BC1820FD0B6B3AFF8A07D18630BDAEE066FEFB2D92F477C24",
            "coinDecimals": 18,
            "coinDenom": "AXS",
            "coinGeckoId": "axie-infinity",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/axs.svg",
            "coinMinimalDenom": "axs-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/D27DDDF34BB47E5D5A570742CC667DE53277867116CCCA341F27785E899A70F3",
            "coinDecimals": 18,
            "coinDenom": "MKR",
            "coinGeckoId": "maker",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/mkr.svg",
            "coinMinimalDenom": "mkr-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/BD796662F8825327D41C96355DF62045A5BA225BAE31C0A86289B9D88ED3F44E",
            "coinDecimals": 18,
            "coinDenom": "RAI",
            "coinGeckoId": "rai",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/rai.svg",
            "coinMinimalDenom": "rai-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/19305E20681911F14D1FB275E538CDE524C3BF88CF9AE5D5F78F4D4DA05E85B2",
            "coinDecimals": 18,
            "coinDenom": "SHIB",
            "coinGeckoId": "shiba-inu",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/shib.svg",
            "coinMinimalDenom": "shib-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/AE2719773D6FCDD05AC17B1ED63F672F5F9D84144A61965F348C86C2A83AD161",
            "coinDecimals": 18,
            "coinDenom": "UNI",
            "coinGeckoId": "uniswap",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/uni.svg",
            "coinMinimalDenom": "uni-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/B901BEC1B71D0573E6EE874FEC39E2DF4C2BDB1DB74CB3DA0A9CACC4A435B0EC",
            "coinDecimals": 18,
            "coinDenom": "XCN",
            "coinGeckoId": "chain-2",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/xcn.svg",
            "coinMinimalDenom": "xcn-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/1E26DB0E5122AED464D98462BD384FCCB595732A66B3970AE6CE0B58BAE0FC49",
            "coinDecimals": 18,
            "coinDenom": "GLMR",
            "coinGeckoId": "moonbeam",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/glmr.svg",
            "coinMinimalDenom": "wglmr-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/903A61A498756EA560B85A85132D3AEE21B5DEDD41213725D22ABF276EA6945E",
            "coinDecimals": 6,
            "coinDenom": "AXL",
            "coinGeckoId": "axelar",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/axl.svg",
            "coinMinimalDenom": "uaxl",
            "contractAddress": undefined,
            "gasPriceStep": {
              "average": 0.007,
              "high": 0.01,
              "low": 0.007,
            },
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/5E2DFDF1734137302129EA1C1BA21A580F96F778D4F021815EA4F6DB378DA1A4",
            "coinDecimals": 18,
            "coinDenom": "FTM",
            "coinGeckoId": "fantom",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/ftm.svg",
            "coinMinimalDenom": "wftm-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/231FD77ECCB2DB916D314019DA30FE013202833386B1908A191D16989AD80B5A",
            "coinDecimals": 6,
            "coinDenom": "polygon.USDC",
            "coinGeckoId": "usd-coin",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/polygon.usdc.svg",
            "coinMinimalDenom": "polygon-uusdc",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": "collateralized",
            "type": undefined,
          },
          {
            "base": "ibc/F17C9CA112815613C5B6771047A093054F837C3020CBA59DFFD9D780A8B2984C",
            "coinDecimals": 6,
            "coinDenom": "avalanche.USDC",
            "coinGeckoId": "usd-coin",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/avalanche.usdc.svg",
            "coinMinimalDenom": "avalanche-uusdc",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": "collateralized",
            "type": undefined,
          },
          {
            "base": "ibc/18FB5C09D9D2371F659D4846A956FA56225E377EE3C3652A2BF3542BF809159D",
            "coinDecimals": 18,
            "coinDenom": "FIL",
            "coinGeckoId": "filecoin",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/fil.svg",
            "coinMinimalDenom": "wfil-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/10E5E5B06D78FFBB61FD9F89209DEE5FD4446ED0550CBB8E3747DA79E10D9DC6",
            "coinDecimals": 18,
            "coinDenom": "ARB",
            "coinGeckoId": "arbitrum",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/arb.svg",
            "coinMinimalDenom": "arb-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/E47F4E97C534C95B942729E1B25DBDE111EA791411CFF100515050BEA0AC0C6B",
            "coinDecimals": 18,
            "coinDenom": "PEPE",
            "coinGeckoId": "pepe",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/pepe.svg",
            "coinMinimalDenom": "pepe-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/4D7A6F2A7744B1534C984A21F9EDFFF8809FC71A9E9243FFB702073E7FCA513A",
            "coinDecimals": 18,
            "coinDenom": "cbETH",
            "coinGeckoId": "coinbase-wrapped-staked-eth",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/cbeth.png",
            "coinMinimalDenom": "cbeth-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/E610B83FD5544E00A8A1967A2EB3BEF25F1A8CFE8650FE247A8BD4ECA9DC9222",
            "coinDecimals": 18,
            "coinDenom": "rETH",
            "coinGeckoId": "rocket-pool-eth",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/reth.png",
            "coinMinimalDenom": "reth-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/81F578C39006EB4B27FFFA9460954527910D73390991B379C03B18934D272F46",
            "coinDecimals": 18,
            "coinDenom": "sfrxETH",
            "coinGeckoId": "staked-frax-ether",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/sfrxeth.svg",
            "coinMinimalDenom": "sfrxeth-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/B2BD584CD2A0A9CE53D4449667E26160C7D44A9C41AF50F602C201E5B3CCA46C",
            "coinDecimals": 18,
            "coinDenom": "wstETH.axl",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/wsteth.axl.svg",
            "coinMinimalDenom": "wsteth-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
          {
            "base": "ibc/FBB3FEF80ED2344D821D4F95C31DBFD33E4E31D5324CAD94EF756E67B749F668",
            "coinDecimals": 18,
            "coinDenom": "YieldETH",
            "coinGeckoId": undefined,
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/yieldeth.svg",
            "coinMinimalDenom": "yieldeth-wei",
            "contractAddress": undefined,
            "gasPriceStep": undefined,
            "pegMechanism": undefined,
            "type": undefined,
          },
        ],
        "explorerUrlToTx": "https://axelarscan.io/tx/{txHash}",
        "features": [
          "ibc-transfer",
          "ibc-go",
          "axelar-evm-bridge",
        ],
        "feeCurrencies": [
          {
            "base": "ibc/903A61A498756EA560B85A85132D3AEE21B5DEDD41213725D22ABF276EA6945E",
            "coinDecimals": 6,
            "coinDenom": "AXL",
            "coinGeckoId": "axelar",
            "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/axl.svg",
            "coinMinimalDenom": "uaxl",
            "contractAddress": undefined,
            "gasPriceStep": {
              "average": 0.007,
              "high": 0.01,
              "low": 0.007,
            },
            "type": undefined,
          },
        ],
        "prettyChainName": "Axelar",
        "rest": "https://lcd-axelar.keplr.app",
        "rpc": "https://rpc-axelar.keplr.app",
        "stakeCurrency": {
          "base": "ibc/903A61A498756EA560B85A85132D3AEE21B5DEDD41213725D22ABF276EA6945E",
          "coinDecimals": 6,
          "coinDenom": "AXL",
          "coinGeckoId": "axelar",
          "coinImageUrl": "${process.env.NEXT_PUBLIC_BASEPATH}/tokens/generated/axl.svg",
          "coinMinimalDenom": "uaxl",
        },
      }
    `);
  });
});

describe("getChainList", () => {
  afterEach(() => {
    jest.resetModules();
  });

  it("should return the correct chain information when OSMOSIS_CHAIN_ID_OVERWRITE is not set", async () => {
    // Set OSMOSIS_CHAIN_ID_OVERWRITE to undefined
    delete process.env.NEXT_PUBLIC_OSMOSIS_CHAIN_ID_OVERWRITE;

    const getChainList = await import("../utils").then(
      (module) => module.getChainList
    );

    const result = getChainList({
      assetLists: AssetLists,
      chains: MockChains,
      environment: "mainnet",
    });
    const expectedChainId = "osmosis-1";

    expect(result).toBeDefined();
    expect(result.length).toBeGreaterThan(0);
    expect(result[0]?.chain_id).toBe(expectedChainId);
    expect(result[0]?.bech32_prefix).toBe("osmo");
  });

  it("should return the correct chain information when OSMOSIS_CHAIN_ID_OVERWRITE is set", async () => {
    // Set OSMOSIS_CHAIN_ID_OVERWRITE to a custom value
    process.env.NEXT_PUBLIC_OSMOSIS_CHAIN_ID_OVERWRITE = "custom-chain-id";

    const getChainList = await import("../utils").then(
      (module) => module.getChainList
    );

    const assetLists = [
      { ...AssetLists[0], chain_id: "custom-chain-id" },
      ...AssetLists.slice(1),
    ];

    const result = getChainList({
      assetLists: assetLists,
      chains: MockChains,
      environment: "mainnet",
    });
    const expectedChainId = "custom-chain-id";

    expect(result).toBeDefined();
    expect(result.length).toBeGreaterThan(0);
    expect(result[0]?.chain_id).toBe(expectedChainId);
    expect(result[0]?.bech32_prefix).toBe("osmo");
  });
});
