import { AmountConfig, IFeeConfig } from "@keplr-wallet/hooks";
import { ChainGetter, IQueriesStore } from "@keplr-wallet/stores";
import { AppCurrency } from "@keplr-wallet/types";
import { CoinPretty, IntPretty, RatePretty } from "@keplr-wallet/unit";
import { OptimizedRoutes, Pool, RoutePathWithAmount } from "@osmosis-labs/pools";
import { ObservableQueryPools } from "../queries";
export declare class ObservableTradeTokenInConfig extends AmountConfig {
    protected readonly observableQueryPools: ObservableQueryPools;
    protected _pools: Pool[];
    protected _inCurrencyMinimalDenom: string | undefined;
    protected _outCurrencyMinimalDenom: string | undefined;
    protected _error: Error | undefined;
    constructor(chainGetter: ChainGetter, queriesStore: IQueriesStore, observableQueryPools: ObservableQueryPools, initialChainId: string, sender: string, feeConfig: IFeeConfig | undefined, pools: Pool[]);
    setPools(pools: Pool[]): void;
    setSendCurrency(currency: AppCurrency | undefined): void;
    setOutCurrency(currency: AppCurrency | undefined): void;
    switchInAndOut(): void;
    get pools(): Pool[];
    requery(): void;
    get sendCurrency(): AppCurrency;
    get outCurrency(): AppCurrency;
    protected get currencyMap(): Map<string, AppCurrency>;
    get sendableCurrencies(): AppCurrency[];
    protected get optimizedRoutes(): OptimizedRoutes;
    get optimizedRoutePaths(): RoutePathWithAmount[];
    get expectedSwapResult(): {
        amount: CoinPretty;
        beforeSpotPriceWithoutSwapFeeInOverOut: IntPretty;
        beforeSpotPriceWithoutSwapFeeOutOverIn: IntPretty;
        beforeSpotPriceInOverOut: IntPretty;
        beforeSpotPriceOutOverIn: IntPretty;
        afterSpotPriceInOverOut: IntPretty;
        afterSpotPriceOutOverIn: IntPretty;
        effectivePriceInOverOut: IntPretty;
        effectivePriceOutOverIn: IntPretty;
        tokenInFeeAmount: CoinPretty;
        swapFee: RatePretty;
        slippage: RatePretty;
    };
    get error(): Error | undefined;
    setError(error: Error | undefined): void;
}
