export const MOCK_tokenRows = [
  {
    image: "",
    name: "MARS",
    perc: 18.87,
    platform: "Osmosis",
    strategyMethod: "Lending",
  },
  {
    image: "",
    name: "OSMO",
    perc: 22.87,
    platform: "Quasar",
    strategyMethod: "Vaults",
  },
  {
    image: "",
    name: "ETH",
    perc: 13.87,
    platform: "Osmosis Dex",
    strategyMethod: "Perp LP",
  },
  {
    image: "",
    name: "ATOM",
    perc: 23.87,
    platform: "Mars",
    strategyMethod: "Staking",
  },
  {
    image: "",
    name: "OSMO",
    perc: 22.87,
    platform: "Osmosis",
    strategyMethod: "Vaults",
  },
  {
    image: "",
    name: "MARS",
    perc: 18.87,
    platform: "Osmosis Dex",
    strategyMethod: "Lending",
  },
  {
    image: "",
    name: "ETH",
    perc: 13.87,
    platform: "Quasar",
    strategyMethod: "LP",
  },
  {
    image: "",
    name: "ATOM",
    perc: 23.87,
    platform: "Levana",
    strategyMethod: "Staking",
  },
  {
    image: "",
    name: "OSMO",
    perc: 22.87,
    platform: "Osmosis Dex",
    strategyMethod: "Perp LP",
  },
  {
    image: "",
    name: "MARS",
    perc: 18.87,
    platform: "Osmosis",
    strategyMethod: "Lending",
  },
  {
    image: "",
    name: "ETH",
    perc: 13.87,
    platform: "Mars",
    strategyMethod: "Staking",
  },
  {
    image: "",
    name: "ATOM",
    perc: 23.87,
    platform: "Quasar",
    strategyMethod: "Vaults",
  },
];
