name: Add new issues to project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to front-end project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/osmosis-labs/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
